### ISSUE TITLE
Vestaboard on Raspian PI OS

### ISSUE THREAD

**Issue by guenter-ms** [SonicRift/Vestaboard#9] opened 2021-02-18 17:39 UTC
Hi Shane again!

I'm still happy with everything and now hanging on the last step to get the simulator work on my raspi with raspian pi os. I didn't get it work in chromium-os or firefox browser. The website comes, the layout of the board is shown but the digits are deep black and do not show anything. The same URL works fine on macOS safari browser.

Did you get it work?

Thanks and take care!
Guenter

**Comment by SonicRift** [comment] 2021-02-18 18:02
Good day Guenter!
I'm assuming you're referring to the simulator that's displayable in the browser? I haven't tested that, but let me see if I can try it out!
I am going to go ahead and close this issue - I'm not affiliated with Vestaboard and this relates to their website and simulator, not my code to interact with their API.
I'd be happy to keep chatting with you about this and see if we can't get it working, though - shoot me an email and I'll help out, or you can feel free to comment back here even after the issue is closed. I'm sure we can figure it out!

Cheers,
Shane

**Closed by SonicRift** 2021-02-18 18:02 UTC

**Comment by guenter-ms** [comment] 2021-02-19 08:40
Good Morning Shane!

you’re right this is not related to your software. Nice from you to have a look inside. 

I saw you on facebook, young boy… I’m just retired after 45 years working in a computer center f-i.de, serving all saving banks in germany with complete IT. I did a lot of programming long time ago, but complete different environments like IBM. Todays software is much more complex and partly hard for me to work with it, but I give my best. 

And I’m also related with aviation and flying since 30 years and have a small plane https://www.planepictures.net/v3/show.php?id=1086539 You like flying swell? US is a paradise for that.

Very nice to hear from you!
Guenter


Am 18.02.2021 um 19:02 schrieb Shane Sutro <notifications@github.com>:


Good day Guenter!
I'm assuming you're referring to the simulator that's displayable in the browser? I haven't tested that, but let me see if I can try it out!
I am going to go ahead and close this issue - I'm not affiliated with Vestaboard and this relates to their website and simulator, not my code to interact with their API.
I'd be happy to keep chatting with you about this and see if we can't get it working, though - shoot me an email and I'll help out, or you can feel free to comment back here even after the issue is closed. I'm sure we can figure it out!

Cheers,
Shane
